version: "3.8"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "345MB"