# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

vars:
  DOCKER_TAG: rinha:latest

tasks:
  clear:
    cmds:
      - rm -rf build

  docker-compose:up:
    desc: start dependencies
    aliases: [d:u]
    cmds:
      - docker-compose up -d

  lint:
    desc: lint code
    aliases: [l]
    cmds:
      # - npx --yes oxlint@latest
      - npx --yes @biomejs/biome check --apply .

  type-check:
    cmds:
      - pnpm --silent type-check

  check:
    desc: check code
    aliases: [c]
    cmds: 
      - task: lint
      - task: type-check

  run:
    desc: run as dev
    aliases: [r]
    cmds:
      - task: lint
      - task: db:setup
      - task: run-only

  run-only:
    desc: run only (no dependencies)
    aliases: [ro]
    ignore_error: true
    env:
      PORT: 9999
      NODE_ENV: production
      # DB_LOGGER: true
    cmds:
      - pnpm run --silent dev

  db:push:
    desc: apply changes to database
    cmds:
      - pnpm --silent drizzle-kit push:pg

  db:create-migration:
    cmds:
      - pnpm drizzle-kit generate:pg init

  db:setup:
    desc: setup database
    aliases: [d:s]
    cmds:
      - pnpm --silent esno src/db/seed.ts

  docker:build:
    cmds:
      - docker build . -t {{.DOCKER_TAG}}
  
  docker:sh:
    cmds:
      - task: docker:build
      - docker run --entrypoint /bin/sh -it {{.DOCKER_TAG}}